export const geohashTableLegends = [
  {
    id: 1,
    geohashLength: 1,
    label: '1 ≤',
    width: '5,000km',
    height: '5,000km',
  },
  {
    id: 2,
    geohashLength: 2,
    label: '2 ≤',
    width: '1,250km',
    height: '625km',
  },
  {
    id: 3,
    geohashLength: 3,
    label: '3 ≤',
    width: '156km',
    height: '156km',
  },
  {
    id: 4,
    geohashLength: 4,
    label: '4 ≤',
    width: '39.1km',
    height: '19.5km',
  },
  {
    id: 5,
    geohashLength: 5,
    label: '5 ≤',
    width: '4.89km',
    height: '4.89km',
  },
  {
    id: 6,
    geohashLength: 6,
    label: '6 ≤',
    width: '1.22km',
    height: '0.61km',
  },
  {
    id: 7,
    geohashLength: 7,
    label: '7 ≤',
    width: '153m',
    height: '153m',
  },
  {
    id: 8,
    geohashLength: 8,
    label: '8 ≤',
    width: '38.2m',
    height: '19.1m',
  },
  {
    id: 9,
    geohashLength: 9,
    label: '9 ≤',
    width: '4.77m',
    height: '4.77m',
  },
  {
    id: 10,
    geohashLength: 10,
    label: '10 ≤',
    width: '1.19m',
    height: '0.596m',
  },
  {
    id: 11,
    geohashLength: 11,
    label: '11 ≤',
    width: '149mm',
    height: '149mm',
  },
  {
    id: 12,
    geohashLength: 12,
    label: '12 ≤',
    width: '37.2mm',
    height: '18.6mm',
  },
]
